apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deploy
  labels:
    app: catalogue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: catalogue
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 2
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 992382386864.dkr.ecr.us-east-1.amazonaws.com/catalogue:300
        ports:
        - containerPort: 80

---
#ClusterIp service
apiVersion: v1
kind: Service
metadata:
  name: catalogue-svc
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080